-   id: wiz-iac
    name: '✨ Wiz - Scan for IaC configuration issues'
    description: Scans for IAC configuration issues
    entry: wiz-iac
    language: python
    pass_filenames: false
    args: [--path, '.']